CREATE DATABASE IF NOT EXISTS ree;
USE ree;

CREATE TABLE IF NOT EXISTS my_table (
    id INT ,
    coordinates POLYGON NOT NULL,  -- Geometry field
    SHAPE_AREA DOUBLE,
    OWNERNAME VARCHAR(255),
    PARCEL_LANDUSE VARCHAR(255),
    DISTRICT_NAME_D VARCHAR(255),
    SUBDIV_NAME VARCHAR(255),
    CITY_NAME VARCHAR(255),
    MUNCP_NAME VARCHAR(255),
    PARCEL_STATUS VARCHAR(255),
    MUNCP_ID INT,
    BLOCK_NO VARCHAR(255),
    SUBDIV_NO VARCHAR(255),
    PARCEL_NO VARCHAR(255),
    NOTES TEXT,
    CONSTRUCTION_TYPE VARCHAR(255),
    SPLIT_TYPE INT,
    SUBDIV_TYPE VARCHAR(255),
    MUNCP_DESC VARCHAR(255),
    OBJECTID INT
);
